### ISSUE TITLE
#21 | Implement read/write settings

### ISSUE THREAD

**Issue by Neelzee** [Neelzee/nmide#23]
# Tasks
- [ ] Function to update settings-file
- [ ] Test update function
- [ ] Function to load settings-file
- [ ] Test load function
